Remove quote
pandacrew/diosteama pull request #31
Opened 2021-04-22 22:23 UTC by ambatlle

* scripts/alterDeleteFlagToQuotes.sql must be executed previously to run remove quote new comment, it creates a new necessary column to mark the quotes as removed
* commands/main.go adds the new rmquote command invocation
* commands/quotes.go adds the controller method to remove quote
* database/quotes.go adds thow methods, FindQuoteById to find a quote by it's id, MarkQuoteAsRemoved which updates the removed column with current timestamp to mark the quote as erased.

2021-04-22 22:27 UTC, ambatlle commented
to execute sql script

cat scripts/alterDeleteFlagToQuotes.sql | docker exec -i diosteama_db_1 psql -U <user>

2021-04-24 11:41 UTC, javipolo requested changes

2021-04-24 11:41 UTC, javipolo commented on commands/main.go
> +	case "rmquote":
Use delquote better, for historical reasons (it was the command in the irc bot)

2021-04-26 10:58 UTC, ambatlle commented on commands/main.go
> +	case "rmquote":
Change done, not tested yet

2021-04-26 23:56 UTC, itorres commented
Todos estos cambios están dentro de #33 por lo que cerramos esta PR.

2021-04-26 23:56 UTC, closed without merging