Patron new command
pandacrew/diosteama pull request #33
Opened 2021-04-24 10:33 UTC by ambatlle

@itorres @javipolo @ZUNbado look at it and feel free to make any comment to improve it

2021-04-24 11:42 UTC, javipolo approved these changes

2021-04-26 23:35 UTC, itorres commented on commands/main.go
> +	fn := invokers[cmd]
Si el comando no existe `invokers[cmd]` tiene valor nil y casca, se puede arreglar con 
```go
	fn, ok := invokers[cmd]
	if ok {
		fn(update, bot, args)
	} else {
	 	// error_handling()
	}
}
```
Ejemplo: https://play.golang.org/p/tINHgGw6boR

2021-04-26 23:37 UTC, itorres commented on commands/nicks.go
> +				reply = "Tu ya eres"
Esto debería decir algo más que "Tú ya eres"

2021-04-26 23:40 UTC, itorres commented on database/quotes.go
> +		log.Printf("[Info] Error consultando DB: %s", err)
Si es un error no es [Info]

2021-04-26 23:44 UTC, itorres commented on database/quotes.go
> +		log.Printf("[Info] Error consultando DB: %s", err)
Ah, que [Info] es la función, he dicho culo.

2021-04-26 23:54 UTC, itorres requested changes
Un problema de esta PR es que dice que es para el comando `!patron` pero se ha juntado la funcionalidad de `!delquote`. En el futuro es mejor mantener las PR separadas por funcionalidad.

2021-04-26 23:54 UTC, itorres commented on commands/main.go
> +  "delquote": removeQuote
`remove` es diferente a `delete`, si usamos `delquote` como comando por coherencia la función debería ser `delquote`

2021-04-26 23:54 UTC, itorres commented on commands/quotes.go
> +func removeQuote(update tgbotapi.Update, bot *tgbotapi.BotAPI, argv []string) {
cambiar a `delQuote`

2021-04-26 23:54 UTC, itorres commented on commands/quotes.go
> +		reply = "Error. Format is !rmquote <quote id>"
El comando no es `!rmquote` sino `!delquote`

2021-04-26 23:54 UTC, itorres commented on commands/quotes.go
> +		reply = "Error. Format is !rmquote <quote id>"
Igual que el anterior

2021-04-26 23:54 UTC, itorres commented on commands/quotes.go
> +		reply = fmt.Sprintf("Quote %d removed!", quoteId)
cambiar removed, removing en las líneas anteriores por deleted, deleting, etc

2021-04-26 23:54 UTC, itorres commented on database/quotes.go
> +		 FROM linux_gey_db WHERE removed is null`
cambiar `removed` por `deleted`, justificación en el archivo SQL

2021-04-26 23:54 UTC, itorres commented on database/quotes.go
> +	FROM linux_gey_db WHERE removed is null AND LOWER(quote) LIKE LOWER('%%%s%%');`, pq)
cambiar `removed` por `deleted`, justificación en el archivo SQL

2021-04-26 23:54 UTC, itorres commented on database/quotes.go
> +	FROM linux_gey_db WHERE removed is null AND LOWER(quote) LIKE LOWER('%%%s%%')
cambiar `removed` por `deleted`, justificación en el archivo SQL

2021-04-26 23:54 UTC, itorres commented on database/quotes.go
> +	query := "select count(*) as c, split_part(author, '!', 1) as a from linux_gey_db where removed is null group by a order by c desc limit $1;"
cambiar `removed` por `deleted`, justificación en el archivo SQL

2021-04-26 23:54 UTC, itorres commented on database/quotes.go
> +// Pre-requisite: 1st time needs to run "scripts/alterDeleteFlagToQuotes.sql" file in DB to add column
Cambiar en esta función todo lo que sea `Removed` por `Deleted`

Plantear también cambiar la función por `DelQuote` o `DeleteQuote` por coherencia.

2021-04-26 23:54 UTC, itorres commented on scripts/alterDeleteFlagToQuotes.sql
> +ALTER TABLE linux_gey_db ADD COLUMN REMOVED TIMESTAMP;
`removed` significa separado o distante, no significa eliminado o borrado. Cambiar por `deleted` por coherencia con el comando `delquote`

2021-04-27 18:11 UTC, ambatlle commented on commands/main.go
> +  "delquote": removeQuote
Ahhh coñe, debí hacer branch de la misma 

> Un problema de esta PR es que dice que es para el comando `!patron` pero se ha juntado la funcionalidad de `!delquote`. En el futuro es mejor mantener las PR separadas por funcionalidad.

Mea culpa, reviso, debí hacer branch desde de la branch remove quote

2021-05-06 23:55 UTC, itorres approved these changes

2021-05-06 23:55 UTC, merged